test_normal_sql: |-
  SELECT /*+ hint_hint_hint */ BOOK_ID AS "bookId", BOOK_NAME AS "bookName", BOOK_PRICE AS "bookPrice", (SELECT BOOK_TYPE_NAME FROM BOOK_TYPE WHERE BOOK_TYPE.BOOK_TYPE_CODE = BOOK.BOOK_TYPE_CODE) AS "bookTypeName"
  FROM BOOK
  WHERE ((BOOK_PRICE > 15.60 AND BOOK_NAME LIKE 'Hello%' AND EXISTS (SELECT * FROM BOOK_AUTHOR_MAP WHERE BOOK_AUTHOR_MAP.BOOK_ID = BOOK.BOOK_ID) AND NOT EXISTS (SELECT * FROM BOOK_AUTHOR_MAP WHERE BOOK_AUTHOR_MAP.BOOK_ID = BOOK.BOOK_ID)) OR (BOOK_ID BETWEEN 10 AND 1000 AND BOOK_NAME IS NOT NULL AND BOOK_PRICE IS NULL))
  ORDER BY BOOK_ID ASC, BOOK_NAME DESC, BOOK_PRICE
  LIMIT 100
  OFFSET 5
  FOR UPDATE
  WAIT 5

